In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import pandas as pd

df = pd.read_csv("../data/products.csv")

df.head()

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams

In [4]:
df.shape

(1597, 27)

In [5]:
df.columns

Index(['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded',
       'dateUpdated', 'dimension', 'ean', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'prices', 'reviews.date',
       'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating',
       'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username', 'sizes',
       'upc', 'weight'],
      dtype='str')

In [6]:
df.isnull().sum()

id                         0
asins                      0
brand                      0
categories                 0
colors                   823
dateAdded                  0
dateUpdated                0
dimension               1032
ean                      699
keys                       0
manufacturer             632
manufacturerNumber       695
name                       0
prices                     0
reviews.date             380
reviews.doRecommend     1058
reviews.numHelpful       697
reviews.rating           420
reviews.sourceURLs         0
reviews.text               0
reviews.title             17
reviews.userCity        1597
reviews.userProvince    1597
reviews.username          17
sizes                   1597
upc                      699
weight                   911
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1597 entries, 0 to 1596
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1597 non-null   str
 1   asins                 1597 non-null   str
 2   brand                 1597 non-null   str
 3   categories            1597 non-null   str
 4   colors                774 non-null    str
 5   dateAdded             1597 non-null   str
 6   dateUpdated           1597 non-null   str
 7   dimension             565 non-null    str
 8   ean                   898 non-null    float64
 9   keys                  1597 non-null   str
 10  manufacturer          965 non-null    str
 11  manufacturerNumber    902 non-null    str
 12  name                  1597 non-null   str
 13  prices                1597 non-null   str
 14  reviews.date          1217 non-null   str
 15  reviews.doRecommend   539 non-null    object
 16  reviews.numHelpful    900 non-null    float64
 17  reviews.rating        1177 non-null   float64
 18  reviews.sourceURLs    1597 non-null   str
 19  reviews.text          1597 non-null   str
 20  reviews.title         1580 non-null   str
 21  reviews.userCity      0 non-null      float64
 22  reviews.userProvince  0 non-null      float64
 23  reviews.username      1580 non-null   str
 24  sizes                 0 non-null      float64
 25  upc                   898 non-null    float64
 26  weight                686 non-null    str
dtypes: float64(7), object(1), str(19)
memory usage: 17.2+ MB

In [8]:
df.head()

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams

In [10]:
products = df[
    [
        "id",
        "name",
        "brand",
        "categories",
        "reviews.text",
        "reviews.rating",
        "reviews.username"
    ]
]

products.head()

,id,name,brand,categories,reviews.text,reviews.rating,reviews.username
0,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",I initially had trouble deciding between the p...,5.0,Cristina M
1,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",Allow me to preface this with a little history...,5.0,Ricky
2,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",I am enjoying it so far. Great for reading. Ha...,4.0,Tedd Gardiner
3,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",I bought one of the first Paperwhites and have...,5.0,Dougal
4,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",I have to say upfront - I don't like coroporat...,5.0,Miljan David Tanic

In [11]:
products["reviews.rating"] = products["reviews.rating"].fillna(0)

products["reviews.username"] = products["reviews.username"].fillna("Anonymous")

In [12]:
products["description"] = (
    products["name"].fillna("") + " " +
    products["brand"].fillna("") + " " +
    products["categories"].fillna("") + " " +
    products["reviews.text"].fillna("")
)

products.head()

,id,name,brand,categories,reviews.text,reviews.rating,reviews.username,description
0,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",I initially had trouble deciding between the p...,5.0,Cristina M,"Kindle Paperwhite Amazon Amazon Devices,mazon...."
1,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",Allow me to preface this with a little history...,5.0,Ricky,"Kindle Paperwhite Amazon Amazon Devices,mazon...."
2,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",I am enjoying it so far. Great for reading. Ha...,4.0,Tedd Gardiner,"Kindle Paperwhite Amazon Amazon Devices,mazon...."
3,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",I bought one of the first Paperwhites and have...,5.0,Dougal,"Kindle Paperwhite Amazon Amazon Devices,mazon...."
4,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",I have to say upfront - I don't like coroporat...,5.0,Miljan David Tanic,"Kindle Paperwhite Amazon Amazon Devices,mazon...."

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english"
)

tfidf_matrix = tfidf.fit_transform(products["description"])

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(tfidf_matrix)

In [15]:
similarity.shape

(1597, 1597)

In [16]:
def recommend(product_name):
    
    index = products[products["name"] == product_name].index[0]

    similarity_scores = list(enumerate(similarity[index]))

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    recommended_products = similarity_scores[1:6]

    for i, score in recommended_products:
        print(
            products.iloc[i]["name"],
            " | Similarity:",
            round(score, 3)
        )

In [17]:
recommend("Kindle Paperwhite")

Kindle Paperwhite  | Similarity: 1.0
Kindle Paperwhite  | Similarity: 0.261
Kindle Voyage E-reader  | Similarity: 0.259
Certified Refurbished Kindle Voyage E-reader with Special Offers  | Similarity: 0.258
Kindle Oasis with Leather Charging Cover - Black  | Similarity: 0.253

In [18]:
recommend("Kindle Paperwhite")

Kindle Paperwhite  | Similarity: 1.0
Kindle Paperwhite  | Similarity: 0.261
Kindle Voyage E-reader  | Similarity: 0.259
Certified Refurbished Kindle Voyage E-reader with Special Offers  | Similarity: 0.258
Kindle Oasis with Leather Charging Cover - Black  | Similarity: 0.253

In [19]:
products["name"].unique()[:20]

<ArrowStringArray>
[                                                            'Kindle Paperwhite',
                                                               'Kindle Keyboard',
              'Certified Refurbished Amazon Fire TV (Previous Generation - 1st)',
      'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Indigo Fabric',
                                            'Amazon Tap Sling Cover - Tangerine',
                                                          'Kindle Fire HDX 8.9"',
 'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Saddle Tan Leather',
                                                 'Amazon Tap Sling Cover - Blue',
   'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Sandstone Fabric',
                                        'All-New Amazon Fire TV Game Controller',
                                                              'Fire HD 7 Tablet',
                                                'Amazon Fire TV Game Controller',
                                                'Amazon Tap Sling Cover - White',
                                              'Amazon Tap Sling Cover - Magenta',
                                         'Certified Refurbished Kindle E-reader',
                                                'Amazon Tap Sling Cover - Green',
                                            'Kindle Paperwhite E-reader - Black',
                                                          'Kindle Paperwhite 3G',
                                                  'Fire HD 10 Tablet with Alexa',
     'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Merlot Leather']
Length: 20, dtype: str

In [20]:
products["name"].unique()[:20]

<ArrowStringArray>
[                                                            'Kindle Paperwhite',
                                                               'Kindle Keyboard',
              'Certified Refurbished Amazon Fire TV (Previous Generation - 1st)',
      'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Indigo Fabric',
                                            'Amazon Tap Sling Cover - Tangerine',
                                                          'Kindle Fire HDX 8.9"',
 'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Saddle Tan Leather',
                                                 'Amazon Tap Sling Cover - Blue',
   'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Sandstone Fabric',
                                        'All-New Amazon Fire TV Game Controller',
                                                              'Fire HD 7 Tablet',
                                                'Amazon Fire TV Game Controller',
                                                'Amazon Tap Sling Cover - White',
                                              'Amazon Tap Sling Cover - Magenta',
                                         'Certified Refurbished Kindle E-reader',
                                                'Amazon Tap Sling Cover - Green',
                                            'Kindle Paperwhite E-reader - Black',
                                                          'Kindle Paperwhite 3G',
                                                  'Fire HD 10 Tablet with Alexa',
     'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Merlot Leather']
Length: 20, dtype: str

In [23]:
products[products["name"].str.contains("Kindle", case=False, na=False)]["name"].unique()

<ArrowStringArray>
[                                                                        'Kindle Paperwhite',
                                                                           'Kindle Keyboard',
                                                                      'Kindle Fire HDX 8.9"',
                                                     'Certified Refurbished Kindle E-reader',
                                                        'Kindle Paperwhite E-reader - Black',
                                                                      'Kindle Paperwhite 3G',
                                             'Certified Refurbished Kindle E-reader - Black',
                                                                    'Kindle Voyage E-reader',
                                  'Certified Refurbished Kindle Paperwhite E-reader - Black',
                                          'Kindle Oasis with Leather Charging Cover - Black',
                                'Kindle Oasis E-reader with Leather Charging Cover - Walnut',
                                                                   'Kindle E-reader - Black',
                          'Certified Refurbished Kindle Voyage E-reader with Special Offers',
 'Amazon 5W USB Official OEM Charger and Power Adapter for Fire Tablets and Kindle eReaders',
                                                                                    'Kindle',
                                    'Kindle for Kids Bundle with the latest Kindle E-reader',
                                                                         'Kindle Fire HD 7"',
                                                                        'Kindle Fire HDX 7"',
                                'Amazon Kindle Oasis Premium Leather Battery Cover - Walnut',
                                 'Amazon Kindle Oasis Premium Leather Battery Cover - Black']
Length: 20, dtype: str

In [24]:
def recommend(product_name):
    
    matches = products[
        products["name"].str.contains(product_name, case=False, na=False)
    ]

    if matches.empty:
        print("Product not found")
        return

    index = matches.index[0]

    similarity_scores = list(enumerate(similarity[index]))

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    recommended_products = similarity_scores[1:6]

    for i, score in recommended_products:
        print(
            products.iloc[i]["name"],
            "| Similarity:",
            round(score, 3)
        )

In [25]:
recommend("Kindle")

Kindle Paperwhite | Similarity: 1.0
Kindle Paperwhite | Similarity: 0.261
Kindle Voyage E-reader | Similarity: 0.259
Certified Refurbished Kindle Voyage E-reader with Special Offers | Similarity: 0.258
Kindle Oasis with Leather Charging Cover - Black | Similarity: 0.253

In [26]:
unique_products = products.drop_duplicates(subset="name").reset_index(drop=True)

unique_products.head()

,id,name,brand,categories,reviews.text,reviews.rating,reviews.username,description
0,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Amazon,"Amazon Devices,mazon.co.uk",I initially had trouble deciding between the p...,5.0,Cristina M,"Kindle Paperwhite Amazon Amazon Devices,mazon...."
1,AVpfBEWcilAPnD_xTGb7,Kindle Keyboard,Amazon,"Kindle Store,Amazon Devices,Electronics",The Kindle is my first e-ink reader. I own an ...,0.0,Jeffrey Stanley,"Kindle Keyboard Amazon Kindle Store,Amazon Dev..."
2,AVpff7_VilAPnD_xc1E_,Certified Refurbished Amazon Fire TV (Previous...,Amazon,"Categories,Amazon Devices,Streaming Media Players","Having received my Fire TV today, I've been tr...",0.0,Gregory P. Baker,Certified Refurbished Amazon Fire TV (Previous...
3,AV00lzP7GV-KLJ3ac0uk,Amazon Echo Dot Case (fits Echo Dot 2nd Genera...,Amazon,Amazon Devices,I'm a huge fan of the Echo family. I have two ...,5.0,D. Miyao,Amazon Echo Dot Case (fits Echo Dot 2nd Genera...
4,AV1T0_7M-jtxr-f31CoX,Amazon Tap Sling Cover - Tangerine,Amazon,Amazon Devices,I am updating my review from two months ago.. ...,4.0,Jbird,Amazon Tap Sling Cover - Tangerine Amazon Amaz...

In [27]:
unique_products["description"] = (
    unique_products["name"].fillna("") + " " +
    unique_products["brand"].fillna("") + " " +
    unique_products["categories"].fillna("")
)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(unique_products["description"])

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(tfidf_matrix)

In [30]:
def recommend(product_name, top_n=5):

    matches = unique_products[
        unique_products["name"].str.contains(product_name, case=False, na=False)
    ]

    if matches.empty:
        print("Product not found.")
        return

    idx = matches.index[0]

    scores = list(enumerate(similarity[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    print(f"\nRecommended products for '{matches.iloc[0]['name']}':\n")

    count = 0
    for i, score in scores[1:]:
        print(f"{count+1}. {unique_products.iloc[i]['name']} ({score:.2f})")
        count += 1
        if count == top_n:
            break

In [31]:
recommend("Kindle")

Recommended products for 'Kindle Paperwhite':

1. Kindle Paperwhite E-reader - Black (0.43)
2. Kindle Paperwhite 3G (0.40)
3. Certified Refurbished Kindle Paperwhite E-reader - Black (0.34)
4. Kindle (0.30)
5. Kindle Fire HD 7" (0.26)

In [32]:
import pickle

pickle.dump(unique_products, open("products.pkl", "wb"))
pickle.dump(similarity, open("similarity.pkl", "wb"))
pickle.dump(tfidf, open("tfidf.pkl", "wb"))

print("Files saved successfully!")

Files saved successfully!

In [33]:
import os

print(os.getcwd())

c:\Desktop\Building a Recommendation System for E-Commerce\notebook

In [34]:
import os

print(os.listdir())

['EDA.ipynb', 'products.pkl', 'similarity.pkl', 'tfidf.pkl']

In [35]:
import os
print(os.getcwd())
print(os.listdir())

c:\Desktop\Building a Recommendation System for E-Commerce\notebook
['EDA.ipynb', 'products.pkl', 'similarity.pkl', 'tfidf.pkl']