In [8]:
import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [9]:
df=pd.read_csv("/home/venkata/Downloads/Venkatavivek - G40 AIML/Data/feedback.csv")
df.head()

,feedback,sentiment,category
0,"Honestly, i would like to schedule deliveries ...",neutral,feature_request
1,"For some reason, the website response time is ...",negative,performance
2,I am having trouble because the application is...,negative,performance
3,"Honestly, the payment page shows an error I ne...",negative,payment
4,I noticed that the application interface is ea...,negative,ui

In [10]:
df.isnull().sum()

feedback     0
sentiment    0
category     0
dtype: int64

In [11]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Error loading punkt: <urlopen error [Errno -3] Temporary
[nltk_data]     failure in name resolution>
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/venkata/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/venkata/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /home/venkata/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feedback   7000 non-null   object
 1   sentiment  7000 non-null   object
 2   category   7000 non-null   object
dtypes: object(3)
memory usage: 164.2+ KB

In [13]:
print("Dataset Shape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Dataset Shape:
(7000, 3)

Columns:
['feedback', 'sentiment', 'category']

First 5 rows:

,feedback,sentiment,category
0,"Honestly, i would like to schedule deliveries ...",neutral,feature_request
1,"For some reason, the website response time is ...",negative,performance
2,I am having trouble because the application is...,negative,performance
3,"Honestly, the payment page shows an error I ne...",negative,payment
4,I noticed that the application interface is ea...,negative,ui

In [14]:
print("Sentiment Distribution:")
print(df["sentiment"].value_counts())

Sentiment Distribution:
sentiment
negative    4489
neutral     1520
positive     991
Name: count, dtype: int64

In [15]:
print("category Distributions:")
print(df['category'].value_counts())

category Distributions:
category
feature_request    1000
performance        1000
payment            1000
ui                 1000
support            1000
bug                1000
login              1000
Name: count, dtype: int64

In [16]:
def clean_text(text):


    text = text.lower()

    text = re.sub(r"[^a-zA-Z\s]", "", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

In [18]:
sample_text = "THE    Payment is Failing!!!"

cleaned_text = clean_text(sample_text)

print("Original:")
print(sample_text)

print("\nCleaned:")
print(cleaned_text)

Original:
THE    Payment is Failing!!!

Cleaned:
the payment is failing

In [19]:
df["cleaned_feedback"] = df["feedback"].apply(clean_text)

display(
    df[
        ["feedback", "cleaned_feedback"]
    ].head(10)
)

,feedback,cleaned_feedback
0,"Honestly, i would like to schedule deliveries ...",honestly i would like to schedule deliveries i...
1,"For some reason, the website response time is ...",for some reason the website response time is v...
2,I am having trouble because the application is...,i am having trouble because the application is...
3,"Honestly, the payment page shows an error I ne...",honestly the payment page shows an error i nee...
4,I noticed that the application interface is ea...,i noticed that the application interface is ea...
5,"Unfortunately, support took too long to respon...",unfortunately support took too long to respond...
6,"For some reason, please add more payment metho...",for some reason please add more payment method...
7,"Today, please add notifications for price chan...",today please add notifications for price chang...
8,I noticed that please add notifications for pr...,i noticed that please add notifications for pr...
9,"Honestly, the app shows an error after checkou...",honestly the app shows an error after checkout...

In [21]:
def tokenize_text(text):

    return word_tokenize(text)

In [22]:
sample_text = "the payment is failing"

tokens = tokenize_text(sample_text)

print("Original text:")
print(sample_text)

print("\nTokens:")
print(tokens)

Original text:
the payment is failing

Tokens:
['the', 'payment', 'is', 'failing']

In [23]:
df["tokens"] = df["cleaned_feedback"].apply(tokenize_text)

display(
    df[
        ["cleaned_feedback", "tokens"]
    ].head(10)
)

,cleaned_feedback,tokens
0,honestly i would like to schedule deliveries i...,"[honestly, i, would, like, to, schedule, deliv..."
1,for some reason the website response time is v...,"[for, some, reason, the, website, response, ti..."
2,i am having trouble because the application is...,"[i, am, having, trouble, because, the, applica..."
3,honestly the payment page shows an error i nee...,"[honestly, the, payment, page, shows, an, erro..."
4,i noticed that the application interface is ea...,"[i, noticed, that, the, application, interface..."
5,unfortunately support took too long to respond...,"[unfortunately, support, took, too, long, to, ..."
6,for some reason please add more payment method...,"[for, some, reason, please, add, more, payment..."
7,today please add notifications for price chang...,"[today, please, add, notifications, for, price..."
8,i noticed that please add notifications for pr...,"[i, noticed, that, please, add, notifications,..."
9,honestly the app shows an error after checkout...,"[honestly, the, app, shows, an, error, after, ..."

In [24]:
stop_words = set(stopwords.words("english"))

print("Number of stopwords:", len(stop_words))

print("\nSample stopwords:")
print(list(stop_words)[:20])

Number of stopwords: 198

Sample stopwords:
["he's", "mightn't", 'mustn', 'that', 'because', 'up', "weren't", 'why', 'yourselves', "don't", 'd', 'in', 'didn', 'it', 'they', 'hers', 'do', 'ain', 'at', "needn't"]

In [25]:
def remove_stopwords(tokens):
    """
    Remove common English stopwords.
    """

    return [
        word
        for word in tokens
        if word not in stop_words
    ]

In [26]:
df["tokens_no_stopwords"] = df["tokens"].apply(
    remove_stopwords
)

display(
    df[
        [
            "tokens",
            "tokens_no_stopwords"
        ]
    ].head(10)
)

,tokens,tokens_no_stopwords
0,"[honestly, i, would, like, to, schedule, deliv...","[honestly, would, like, schedule, deliveries, ..."
1,"[for, some, reason, the, website, response, ti...","[reason, website, response, time, poor, fix]"
2,"[i, am, having, trouble, because, the, applica...","[trouble, application, lagging, badly, please,..."
3,"[honestly, the, payment, page, shows, an, erro...","[honestly, payment, page, shows, error, need, ..."
4,"[i, noticed, that, the, application, interface...","[noticed, application, interface, easy, use, p..."
5,"[unfortunately, support, took, too, long, to, ...","[unfortunately, support, took, long, respond, ..."
6,"[for, some, reason, please, add, more, payment...","[reason, please, add, payment, methods, please..."
7,"[today, please, add, notifications, for, price...","[today, please, add, notifications, price, cha..."
8,"[i, noticed, that, please, add, notifications,...","[noticed, please, add, notifications, price, c..."
9,"[honestly, the, app, shows, an, error, after, ...","[honestly, app, shows, error, checkout, frustr..."

In [27]:
stemmer = PorterStemmer()
def stem_words(tokens):

    return [
        stemmer.stem(word)
        for word in tokens
    ]

In [28]:
df["stemmed_tokens"] = df["tokens_no_stopwords"].apply(
    stem_words
)

display(
    df[
        [
            "tokens_no_stopwords",
            "stemmed_tokens"
        ]
    ].head(10)
)

,tokens_no_stopwords,stemmed_tokens
0,"[honestly, would, like, schedule, deliveries, ...","[honestli, would, like, schedul, deliveri, nee..."
1,"[reason, website, response, time, poor, fix]","[reason, websit, respons, time, poor, fix]"
2,"[trouble, application, lagging, badly, please,...","[troubl, applic, lag, badli, pleas, look]"
3,"[honestly, payment, page, shows, error, need, ...","[honestli, payment, page, show, error, need, a..."
4,"[noticed, application, interface, easy, use, p...","[notic, applic, interfac, easi, use, pleas, help]"
5,"[unfortunately, support, took, long, respond, ...","[unfortun, support, took, long, respond, pleas..."
6,"[reason, please, add, payment, methods, please...","[reason, pleas, add, payment, method, pleas, h..."
7,"[today, please, add, notifications, price, cha...","[today, pleas, add, notif, price, chang, frust..."
8,"[noticed, please, add, notifications, price, c...","[notic, pleas, add, notif, price, chang]"
9,"[honestly, app, shows, error, checkout, frustr...","[honestli, app, show, error, checkout, frustrat]"

In [29]:
lemmatizer = WordNetLemmatizer()
def lemmatize_words(tokens):

    return [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

In [30]:
df["lemmatized_tokens"] = df["tokens_no_stopwords"].apply(
    lemmatize_words
)

display(
    df[
        [
            "tokens_no_stopwords",
            "lemmatized_tokens"
        ]
    ].head(10)
)

,tokens_no_stopwords,lemmatized_tokens
0,"[honestly, would, like, schedule, deliveries, ...","[honestly, would, like, schedule, delivery, ne..."
1,"[reason, website, response, time, poor, fix]","[reason, website, response, time, poor, fix]"
2,"[trouble, application, lagging, badly, please,...","[trouble, application, lagging, badly, please,..."
3,"[honestly, payment, page, shows, error, need, ...","[honestly, payment, page, show, error, need, a..."
4,"[noticed, application, interface, easy, use, p...","[noticed, application, interface, easy, use, p..."
5,"[unfortunately, support, took, long, respond, ...","[unfortunately, support, took, long, respond, ..."
6,"[reason, please, add, payment, methods, please...","[reason, please, add, payment, method, please,..."
7,"[today, please, add, notifications, price, cha...","[today, please, add, notification, price, chan..."
8,"[noticed, please, add, notifications, price, c...","[noticed, please, add, notification, price, ch..."
9,"[honestly, app, shows, error, checkout, frustr...","[honestly, app, show, error, checkout, frustra..."

In [31]:
df["processed_text"] = df["lemmatized_tokens"].apply(
    lambda tokens: " ".join(tokens)
)

display(
    df[
        [
            "feedback",
            "processed_text",
            "sentiment",
            "category"
        ]
    ].head(10)
)

,feedback,processed_text,sentiment,category
0,"Honestly, i would like to schedule deliveries ...",honestly would like schedule delivery need ass...,neutral,feature_request
1,"For some reason, the website response time is ...",reason website response time poor fix,negative,performance
2,I am having trouble because the application is...,trouble application lagging badly please look,negative,performance
3,"Honestly, the payment page shows an error I ne...",honestly payment page show error need assistance,negative,payment
4,I noticed that the application interface is ea...,noticed application interface easy use please ...,negative,ui
5,"Unfortunately, support took too long to respon...",unfortunately support took long respond please...,negative,support
6,"For some reason, please add more payment metho...",reason please add payment method please help,neutral,feature_request
7,"Today, please add notifications for price chan...",today please add notification price change fru...,neutral,feature_request
8,I noticed that please add notifications for pr...,noticed please add notification price change,neutral,feature_request
9,"Honestly, the app shows an error after checkou...",honestly app show error checkout frustrating,negative,bug

In [33]:
processed_df = df[
    [
        "feedback",
        "processed_text",
        "sentiment",
        "category"
    ]
]

In [34]:
processed_df = df[
    [
        "feedback",
        "processed_text",
        "sentiment",
        "category"
    ]
]

processed_df.to_csv(
    "processed_feedback.csv",
    index=False
)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!