In [1]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
df = pd.read_csv("/home/venkata/Downloads/Venkatavivek - G40 AIML/processed_feedback.csv")

print("Shape:", df.shape)

df.head()

Shape: (7000, 4)

,feedback,processed_text,sentiment,category
0,"Honestly, i would like to schedule deliveries ...",honestly would like schedule delivery need ass...,neutral,feature_request
1,"For some reason, the website response time is ...",reason website response time poor fix,negative,performance
2,I am having trouble because the application is...,trouble application lagging badly please look,negative,performance
3,"Honestly, the payment page shows an error I ne...",honestly payment page show error need assistance,negative,payment
4,I noticed that the application interface is ea...,noticed application interface easy use please ...,negative,ui

In [6]:
vectorizer = TfidfVectorizer()

X_tfidf = vectorizer.fit_transform(
    df["processed_text"]
)

print("TF-IDF shape:")
print(X_tfidf.shape)

TF-IDF shape:
(7000, 168)

In [7]:
feature_names = vectorizer.get_feature_names_out()

print("Number of features:", len(feature_names))

print("\nFirst 50 words:")
print(feature_names[:50])

Number of features: 168

First 50 words:
['access' 'account' 'add' 'app' 'application' 'arriving' 'assistance'
 'back' 'badly' 'becomes' 'blank' 'broken' 'bug' 'button' 'card' 'care'
 'change' 'charged' 'checkout' 'clean' 'clicking' 'close' 'color'
 'complete' 'confusing' 'contacted' 'crash' 'customer' 'dark' 'dashboard'
 'declined' 'deducted' 'delivery' 'design' 'difficult' 'disappointing'
 'displaying' 'download' 'easy' 'error' 'every' 'experience' 'extremely'
 'failed' 'failing' 'file' 'filter' 'find' 'fingerprint' 'fix']

In [8]:
print(X_tfidf[0])

  (0, 63)	0.27528481257003484
  (0, 166)	0.36128877759247824
  (0, 75)	0.42335949857351146
  (0, 125)	0.4847542986827438
  (0, 32)	0.4847542986827438
  (0, 89)	0.268866572457691
  (0, 6)	0.2686870524488556

In [9]:
tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=feature_names
)

tfidf_df.head()

,access,account,add,app,application,arriving,assistance,back,badly,becomes,...,use,useful,user,verify,website,whenever,wishlist,working,would,wrong
0,0.0,0.0,0.0,0.0,0.000000,0.0,0.268687,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.361289,0.0
1,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.448761,0.0,0.0,0.0,0.000000,0.0
2,0.0,0.0,0.0,0.0,0.345743,0.0,0.000000,0.0,0.556408,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
3,0.0,0.0,0.0,0.0,0.000000,0.0,0.309908,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
4,0.0,0.0,0.0,0.0,0.333610,0.0,0.000000,0.0,0.000000,0.0,...,0.475411,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0

In [10]:
row = X_tfidf[0].toarray().flatten()

word_scores = pd.DataFrame({
    "word": feature_names,
    "tfidf": row
})

word_scores = word_scores.sort_values(
    by="tfidf",
    ascending=False
)

word_scores.head(10)

           word     tfidf
125    schedule  0.484754
32     delivery  0.484754
75         like  0.423359
166       would  0.361289
63     honestly  0.275285
89         need  0.268867
6    assistance  0.268687
0        access  0.000000
114     quickly  0.000000
109     problem  0.000000

In [11]:
vocabulary = pd.DataFrame({
    "feature": feature_names
})

vocabulary.to_csv(
    "tfidf_vocabulary.csv",
    index=False
)

print("TF-IDF vocabulary saved successfully!")

TF-IDF vocabulary saved successfully!

In [12]:
print(classification_report(y_test, y_pred))

NameError: name 'classification_report' is not defined