In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MultiLabelBinarizer

from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    classification_report,
    accuracy_score
)

In [3]:
df = pd.read_csv("/content/feedback_multilabel.csv")

print("Dataset shape:", df.shape)

df.head()

Dataset shape: (10500, 3)

,feedback,sentiment,categories
0,The application becomes extremely slow when I ...,negative,performance
1,"For what it's worth, a longer session timeout ...",neutral,login
2,"To be honest, having social login options woul...",neutral,login
3,Biometric login stopped working after the late...,negative,"login,support"
4,Lately everything has been running stably for ...,positive,"bug,feature_request,support"

In [4]:
df["categories"] = df["categories"].apply(
    lambda x: [category.strip() for category in x.split(",")]
)

df.head()

,feedback,sentiment,categories
0,The application becomes extremely slow when I ...,negative,[performance]
1,"For what it's worth, a longer session timeout ...",neutral,[login]
2,"To be honest, having social login options woul...",neutral,[login]
3,Biometric login stopped working after the late...,negative,"[login, support]"
4,Lately everything has been running stably for ...,positive,"[bug, feature_request, support]"

In [5]:
mlb = MultiLabelBinarizer()

y = mlb.fit_transform(df["categories"])

print("Classes:")
print(mlb.classes_)

Classes:
['bug' 'feature_request' 'login' 'payment' 'performance' 'support' 'ui']

In [6]:
y

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 1, 0],
       [1, 0, 1, ..., 0, 1, 0]])

In [7]:
X = df["feedback"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 8400
Testing samples: 2100

In [9]:
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print(X_train_tfidf.shape)

(8400, 758)

In [10]:
model = OneVsRestClassifier(
    LogisticRegression(max_iter=1000)
)

model.fit(X_train_tfidf, y_train)

print("Multi-label model trained!")

Multi-label model trained!

In [16]:
y_pred = model.predict(X_test_tfidf)

print(y_pred)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [1 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [1 0 0 ... 0 1 0]
 [0 0 1 ... 1 1 0]]

In [17]:
print(accuracy_score(y_test, y_pred))

0.9909523809523809

In [12]:
predicted_categories = mlb.inverse_transform(y_pred)

for categories in predicted_categories:
    print(categories)

('bug', 'payment')
('performance',)
('bug', 'performance')
('support', 'ui')
('feature_request',)
('performance', 'ui')
('payment', 'performance', 'ui')
('support', 'ui')
('login', 'ui')
('ui',)
('payment',)
('login',)
('bug', 'login', 'support')
('login', 'support')
('bug', 'performance', 'support')
('feature_request', 'payment')
('feature_request',)
('payment',)
('login', 'payment')
('feature_request', 'login', 'performance')
('payment', 'performance')
('payment', 'ui')
('ui',)
('bug',)
('performance', 'support', 'ui')
('login', 'ui')
('bug', 'login')
('performance', 'ui')
('feature_request', 'payment')
('performance',)
('bug',)
('payment', 'support')
('bug',)
('bug', 'feature_request', 'ui')
('bug',)
('support',)
('feature_request',)
('payment',)
('feature_request',)
('performance',)
('payment',)
('support', 'ui')
('bug', 'ui')
('feature_request', 'performance')
('feature_request', 'login')
('performance', 'ui')
('bug', 'feature_request')
('support', 'ui')
('payment', 'ui')
('feature_request', 'login')
('feature_request',)
('performance', 'support')
('performance',)
('bug',)
('bug', 'payment')
('login', 'payment')
('payment',)
('login',)
('performance', 'support')
('login', 'ui')
('support',)
('bug', 'payment')
('bug', 'performance')
('performance', 'support', 'ui')
('payment', 'performance', 'support')
('login', 'support', 'ui')
('feature_request',)
('feature_request', 'login')
('performance', 'ui')
('payment', 'support', 'ui')
('support',)
('bug', 'payment', 'ui')
('login', 'payment', 'support')
('login', 'performance', 'support')
('performance',)
('bug', 'payment')
('payment',)
('ui',)
('feature_request', 'login')
('feature_request',)
('bug', 'performance', 'ui')
('feature_request',)
('support',)
('feature_request', 'login')
('bug',)
('payment', 'performance', 'ui')
('feature_request',)
('login',)
('performance', 'ui')
('performance',)
('login', 'support')
('payment', 'ui')
('feature_request',)
('performance', 'ui')
('login',)
('payment',)
('login', 'ui')
('feature_request',)
('feature_request', 'login')
('login',)
('bug',)
('bug', 'support')
('ui',)
('bug', 'payment', 'ui')
('bug',)
('performance',)
('bug', 'feature_request', 'support')
('bug', 'payment')
('ui',)
('payment', 'performance', 'ui')
('payment', 'support')
('support', 'ui')
('support', 'ui')
('bug',)
('feature_request', 'support')
('feature_request', 'performance')
('bug', 'support')
('login', 'payment')
('payment',)
('bug', 'payment', 'ui')
('feature_request', 'login', 'performance')
('login', 'ui')
('performance', 'support')
('performance',)
('login', 'support')
('bug', 'feature_request')
('payment',)
('payment',)
('feature_request', 'performance')
('feature_request', 'ui')
('performance',)
('performance', 'ui')
('login', 'support')
('feature_request', 'ui')
('login',)
('feature_request', 'login', 'payment')
('feature_request', 'performance')
('login', 'ui')
('payment', 'ui')
('feature_request', 'payment')
('bug',)
('payment',)
('feature_request', 'ui')
('login', 'ui')
('bug', 'feature_request', 'ui')
('bug', 'ui')
('performance', 'support')
('login',)
('payment', 'performance')
('bug', 'payment')
('payment', 'ui')
('bug', 'performance')
('feature_request', 'performance')
('payment',)
('ui',)
('performance', 'ui')
('performance',)
('bug', 'login', 'support')
('bug', 'ui')
('payment',)
('ui',)
('ui',)
('login',)
('feature_request', 'login')
('feature_request', 'login', 'ui')
('performance',)
('feature_request', 'ui')
('bug', 'payment')
('payment', 'performance')
('bug',)
('feature_request', 'performance')
('payment',)
('feature_request', 'performance', 'ui')
('feature_request', 'payment')
('bug',)
('bug', 'performance')
('payment',)
('performance', 'ui')
('bug', 'ui')
('performance',)
('login',)
('payment',)
('login', 'support')
('payment', 'ui')
('bug', 'payment', 'support')
('feature_request', 'support')
('feature_request', 'login', 'support')
('login', 'ui')
('support',)
('ui',)
('feature_request', 'performance')
('bug',)
('feature_request', 'payment', 'support')
('performance', 'support')
('login',)
('feature_request', 'login')
('bug', 'feature_request', 'ui')
('payment', 'ui')
('support', 'ui')
('feature_request',)
('bug', 'ui')
('feature_request', 'login')
('feature_request', 'payment', 'performance')
('performance',)
('bug', 'ui')
('login', 'support')
('bug', 'login', 'performance')
('bug', 'feature_request', 'login')
('login', 'payment')
('login',)
('performance', 'ui')
('performance',)
('login',)
('payment', 'performance', 'support')
('performance', 'support')
('feature_request', 'performance', 'ui')
('bug', 'feature_request')
('feature_request', 'performance')
('feature_request', 'ui')
('login',)
('login', 'payment')
('bug',)
('payment',)
('payment',)
('login',)
('bug', 'login')
('bug',)
('login', 'ui')
('performance',)
('feature_request',)
('feature_request', 'performance')
('payment', 'support')
('bug', 'login')
('feature_request', 'login')
('feature_request', 'login', 'ui')
('bug', 'payment', 'support')
('bug',)
('support',)
('bug',)
('payment',)
('bug',)
('payment',)
('feature_request',)
('payment',)
('bug', 'support', 'ui')
('ui',)
('bug', 'feature_request', 'login')
('feature_request', 'login')
('payment',)
('feature_request', 'ui')
('bug', 'feature_request')
('bug', 'ui')
('feature_request',)
('feature_request', 'performance', 'ui')
('bug', 'feature_request')
('bug', 'login', 'performance')
('login', 'payment', 'support')
('payment',)
('bug', 'ui')
('feature_request', 'login', 'ui')
('performance',)
('feature_request', 'login', 'payment')
('feature_request', 'login', 'ui')
('payment', 'support')
('payment',)
('support',)
('feature_request',)
('feature_request', 'login')
('feature_request', 'support')
('feature_request', 'performance')
('support',)
('feature_request', 'login')
('feature_request', 'payment')
('login',)
('payment',)
('performance', 'ui')
('feature_request', 'payment')
('feature_request', 'ui')
('feature_request', 'payment', 'ui')
('feature_request', 'support')
('ui',)
('feature_request',)
('login', 'payment')
('feature_request', 'login', 'support')
('support',)
('performance',)
('bug', 'feature_request', 'login')
('feature_request', 'ui')
('ui',)
('performance',)
('performance', 'ui')
('feature_request', 'performance')
('login', 'ui')
('feature_request', 'login', 'support')
('bug', 'feature_request')
('feature_request', 'support')
('bug',)
('payment',)
('performance',)
('login',)
('bug', 'performance', 'support')
('performance',)
('payment',)
('bug', 'support')
('bug', 'support')
('payment',)
('payment',)
('payment',)
('bug', 'login')
('login',)
('feature_request', 'payment')
('feature_request', 'login', 'payment')
('feature_request', 'payment', 'performance')
('feature_request',)
('bug', 'payment')
('payment',)
('login', 'support')
('login',)
('feature_request', 'support')
('performance', 'support')
('support',)
('support', 'ui')
('payment', 'support')
('payment', 'performance')
('bug', 'payment')
('payment',)
('feature_request', 'support')
('payment',)
('login', 'ui')
('bug', 'feature_request', 'support')
('bug', 'support')
('bug', 'feature_request')
('bug', 'login', 'support')
('payment', 'performance')
('feature_request', 'payment', 'support')
('bug', 'payment')
('performance',)
('ui',)
('payment', 'performance')
('login', 'performance')
('payment',)
('login', 'payment', 'ui')
('feature_request', 'login', 'ui')
('login', 'performance')
('bug', 'payment', 'support')
('payment',)
('bug', 'feature_request', 'ui')
('bug',)
('bug', 'login')
('feature_request',)
('bug', 'feature_request', 'payment')
('performance', 'support')
('login',)
('performance',)
('bug', 'login', 'performance')
('performance',)
('feature_request',)
('bug', 'feature_request')
('login', 'ui')
('support', 'ui')
('bug', 'feature_request', 'login')
('feature_request', 'performance')
('feature_request', 'payment')
('login', 'ui')
('bug',)
('feature_request', 'login', 'performance')
('bug', 'performance')
('bug', 'payment', 'support')
('bug', 'feature_request', 'support')
('support',)
('feature_request', 'ui')
('ui',)
('payment',)
('payment',)
('login', 'performance')
('payment', 'support')
('bug', 'ui')
('feature_request', 'support', 'ui')
('feature_request', 'ui')
('performance',)
('feature_request', 'payment', 'ui')
('feature_request', 'ui')
('bug', 'feature_request', 'ui')
('feature_request', 'ui')
('performance', 'ui')
('feature_request',)
('payment', 'performance')
('login', 'ui')
('support', 'ui')
('feature_request', 'payment', 'performance')
('feature_request', 'login', 'payment')
('login', 'support', 'ui')
('login', 'payment')
('feature_request', 'performance')
('support',)
('feature_request', 'performance', 'support')
('payment',)
('payment',)
('performance',)
('bug',)
('performance', 'support')
('bug', 'feature_request', 'ui')
('bug', 'feature_request')
('performance', 'ui')
('login', 'performance', 'support')
('bug', 'feature_request')
('payment',)
('login', 'payment', 'ui')
('bug', 'ui')
('payment', 'ui')
('payment', 'performance')
('performance',)
('bug', 'payment')
('payment', 'support')
('feature_request', 'performance')
('login',)
('payment', 'support')
('feature_request', 'login', 'ui')
('feature_request', 'ui')
('bug',)
('feature_request',)
('feature_request', 'payment')
('feature_request', 'login')
('payment',)
('payment', 'ui')
('login', 'performance', 'support')
('feature_request', 'login')
('bug',)
('ui',)
('performance', 'support')
('bug', 'ui')
('feature_request', 'login')
('login', 'support', 'ui')
('bug', 'login', 'payment')
('feature_request', 'login')
('login',)
('performance',)
('bug',)
('payment',)
('support', 'ui')
('bug', 'feature_request')
('payment',)
('login', 'payment')
('login', 'support', 'ui')
('ui',)
('bug',)
('bug', 'login', 'ui')
('performance',)
('payment', 'performance')
('login', 'support', 'ui')
('feature_request', 'payment', 'support')
('feature_request', 'payment', 'support')
('bug', 'payment')
('feature_request', 'support')
('payment', 'ui')
('login', 'ui')
('login',)
('performance', 'ui')
('support', 'ui')
('bug', 'ui')
('feature_request', 'login', 'payment')
('feature_request', 'performance')
('bug',)
('payment', 'support')
('feature_request',)
('bug', 'feature_request', 'ui')
('ui',)
('login', 'performance')
('feature_request', 'payment', 'ui')
('bug', 'support')
('bug',)
('login',)
('payment', 'performance')
('login',)
('payment',)
('feature_request',)
('bug', 'login', 'payment')
('login', 'performance')
('performance', 'support', 'ui')
('feature_request', 'support')
('performance',)
('feature_request', 'login', 'payment')
('login', 'ui')
('login', 'payment')
('bug',)
('bug', 'performance', 'support')
('support',)
('bug', 'performance', 'ui')
('login', 'ui')
('performance',)
('performance',)
('feature_request', 'performance', 'ui')
('performance', 'ui')
('bug', 'payment')
('ui',)
('payment',)
('performance', 'support')
('payment',)
('performance', 'support', 'ui')
('feature_request', 'performance')
('login', 'support')
('payment',)
('bug', 'payment', 'performance')
('bug', 'feature_request', 'ui')
('payment', 'performance')
('payment', 'performance', 'support')
('feature_request',)
('payment', 'performance')
('login', 'payment')
('performance', 'support')
('feature_request',)
('support', 'ui')
('login',)
('bug', 'payment', 'support')
('feature_request',)
('bug', 'login')
('bug', 'feature_request')
('payment',)
('login', 'support')
('login',)
('payment', 'support')
('payment', 'support')
('payment',)
('support', 'ui')
('login',)
('bug', 'payment')
('feature_request', 'payment')
('login', 'performance', 'support')
('bug', 'feature_request', 'ui')
('support', 'ui')
('login', 'support')
('performance', 'ui')
('performance', 'support')
('login', 'payment')
('payment', 'performance')
('performance', 'support')
('feature_request', 'ui')
('support',)
('payment', 'performance')
('feature_request', 'support')
('bug', 'login')
('bug',)
('payment',)
('performance', 'support')
('bug', 'ui')
('feature_request',)
('feature_request',)
('bug', 'support')
('bug', 'performance')
('feature_request', 'payment')
('ui',)
('payment',)
('performance',)
('bug',)
('bug', 'ui')
('support',)
('login', 'ui')
('login',)
('login',)
('feature_request', 'support')
('feature_request', 'performance')
('performance',)
('login', 'performance')
('payment', 'support')
('login', 'ui')
('bug', 'feature_request')
('feature_request',)
('performance',)
('performance',)
('feature_request',)
('payment',)
('feature_request', 'support')
('bug', 'login', 'performance')
('payment', 'ui')
('bug', 'support')
('payment', 'support')
('feature_request', 'payment', 'performance')
('ui',)
('login', 'performance')
('payment', 'performance')
('support',)
('feature_request', 'payment')
('feature_request', 'login', 'performance')
('performance',)
('ui',)
('performance',)
('login', 'ui')
('payment',)
('login', 'support')
('login', 'performance', 'ui')
('bug', 'feature_request', 'support')
('login', 'performance', 'ui')
('payment', 'support', 'ui')
('bug', 'support')
('payment', 'support')
('payment', 'performance')
('login',)
('performance',)
('feature_request', 'ui')
('support',)
('payment', 'ui')
('ui',)
('payment', 'support')
('feature_request', 'support')
('bug', 'login')
('login',)
('payment',)
('feature_request', 'support')
('payment',)
('support', 'ui')
('login', 'payment')
('bug', 'payment', 'support')
('feature_request', 'performance')
('payment', 'ui')
('login', 'performance', 'support')
('payment', 'performance', 'support')
('login', 'payment')
('bug',)
('login', 'payment')
('feature_request',)
('login',)
('bug', 'payment')
('support',)
('bug', 'payment')
('payment',)
('bug', 'ui')
('login', 'ui')
('support',)
('payment', 'support', 'ui')
('bug', 'login')
('login', 'performance', 'ui')
('feature_request',)
('login', 'payment', 'performance')
('support',)
('bug', 'feature_request')
('bug', 'login', 'support')
('bug', 'feature_request')
('payment', 'performance')
('bug', 'ui')
('ui',)
('ui',)
('payment',)
('payment', 'performance', 'support')
('feature_request', 'payment', 'support')
('login', 'ui')
('bug', 'feature_request', 'login')
('payment',)
('performance',)
('login',)
('feature_request', 'payment', 'ui')
('feature_request', 'payment', 'support')
('login', 'performance')
('login', 'ui')
('feature_request',)
('ui',)
('feature_request',)
('login', 'ui')
('feature_request', 'payment')
('feature_request',)
('bug',)
('payment',)
('payment',)
('feature_request', 'login', 'support')
('login', 'support')
('payment', 'support', 'ui')
('bug', 'payment')
('bug', 'ui')
('login', 'ui')
('login',)
('login', 'performance', 'support')
('bug', 'feature_request')
('feature_request',)
('login',)
('bug', 'performance', 'support')
('login', 'performance', 'support')
('bug', 'performance')
('support',)
('support',)
('ui',)
('performance', 'support')
('login', 'ui')
('ui',)
('performance', 'support')
('bug', 'login')
('bug', 'payment', 'performance')
('payment', 'performance')
('login', 'performance')
('feature_request',)
('bug',)
('payment',)
('support',)
('feature_request', 'performance')
('login',)
('payment',)
('support',)
('feature_request', 'payment')
('bug', 'feature_request')
('feature_request', 'payment', 'performance')
('payment',)
('performance', 'ui')
('login', 'support')
('feature_request', 'login')
('performance',)
('bug', 'feature_request', 'payment')
('performance', 'support')
('feature_request', 'payment')
('bug',)
('login', 'ui')
('ui',)
('ui',)
('performance',)
('performance', 'ui')
('payment', 'support')
('feature_request', 'ui')
('bug', 'ui')
('performance',)
('bug', 'feature_request')
('login', 'ui')
('performance',)
('feature_request', 'performance')
('bug', 'feature_request')
('payment', 'performance', 'ui')
('login', 'ui')
('support',)
('bug',)
('feature_request', 'login')
('payment', 'performance')
('feature_request',)
('feature_request', 'login')
('payment', 'performance', 'support')
('payment',)
('login', 'support', 'ui')
('bug', 'ui')
('login', 'payment', 'support')
('login',)
('feature_request', 'login')
('login', 'support')
('performance', 'support')
('feature_request', 'payment', 'performance')
('login',)
('payment', 'performance', 'support')
('performance',)
('bug',)
('bug',)
('login', 'support')
('feature_request', 'login')
('feature_request', 'login')
('payment', 'ui')
('login',)
('login', 'payment')
('bug', 'ui')
('bug', 'support')
('feature_request',)
('ui',)
('performance',)
('bug', 'feature_request', 'ui')
('login', 'payment', 'performance')
('login',)
('feature_request', 'support', 'ui')
('performance', 'support')
('ui',)
('feature_request', 'payment', 'ui')
('login', 'ui')
('login', 'support', 'ui')
('bug',)
('login', 'performance')
('bug', 'support', 'ui')
('login', 'payment')
('login', 'performance')
('ui',)
('payment', 'performance')
('feature_request', 'payment')
('feature_request',)
('login',)
('bug', 'support')
('bug', 'performance')
('feature_request', 'performance', 'support')
('feature_request', 'payment')
('feature_request',)
('login', 'payment')
('bug', 'login')
('bug',)
('feature_request', 'login', 'payment')
('support',)
('login', 'performance')
('login', 'ui')
('performance',)
('performance', 'ui')
('feature_request',)
('bug', 'performance')
('bug', 'login')
('ui',)
('feature_request', 'login', 'ui')
('feature_request',)
('payment',)
('bug', 'payment', 'performance')
('login', 'ui')
('bug', 'performance')
('bug', 'support')
('feature_request', 'ui')
('feature_request',)
('performance',)
('login', 'support')
('payment',)
('bug',)
('payment',)
('feature_request',)
('payment', 'ui')
('feature_request', 'support')
('ui',)
('login',)
('payment',)
('performance',)
('login', 'performance')
('payment',)
('payment', 'support')
('bug',)
('performance',)
('payment', 'performance')
('performance',)
('performance', 'ui')
('payment',)
('login', 'performance', 'support')
('login', 'performance', 'ui')
('feature_request', 'payment', 'performance')
('bug', 'performance')
('login', 'support')
('performance',)
('feature_request',)
('feature_request', 'payment')
('bug', 'support')
('login', 'payment', 'performance')
('payment', 'support')
('payment', 'support')
('support', 'ui')
('feature_request', 'login')
('login', 'payment', 'support')
('payment',)
('feature_request',)
('performance', 'ui')
('performance', 'ui')
('feature_request', 'ui')
('payment',)
('feature_request', 'payment', 'performance')
('bug', 'feature_request', 'login')
('login',)
('payment', 'support', 'ui')
('bug', 'payment', 'performance')
('feature_request', 'support')
('bug', 'performance')
('feature_request',)
('login', 'support')
('performance',)
('payment', 'ui')
('bug', 'support')
('performance', 'support')
('payment', 'ui')
('payment', 'performance', 'ui')
('feature_request', 'performance')
('payment', 'support')
('login',)
('performance',)
('bug', 'payment')
('login',)
('feature_request', 'support', 'ui')
('bug', 'feature_request')
('support', 'ui')
('bug',)
('login', 'ui')
('login',)
('login',)
('bug',)
('support', 'ui')
('feature_request', 'payment')
('feature_request', 'login', 'payment')
('login', 'performance')
('payment', 'ui')
('support',)
('login', 'payment', 'support')
('bug',)
('performance',)
('performance', 'ui')
('bug', 'support')
('bug',)
('login',)
('login', 'support')
('bug', 'performance')
('bug',)
('performance',)
('login', 'performance')
('support',)
('bug', 'feature_request')
('payment', 'performance')
('login', 'payment')
('payment',)
('bug', 'ui')
('bug',)
('bug', 'feature_request', 'payment')
('ui',)
('login',)
('feature_request', 'login')
('feature_request',)
('login', 'payment')
('feature_request', 'support')
('bug',)
('bug', 'performance', 'support')
('bug', 'feature_request', 'support')
('feature_request',)
('payment', 'performance')
('feature_request', 'login')
('feature_request', 'performance')
('bug',)
('bug', 'feature_request', 'payment')
('ui',)
('bug', 'login', 'support')
('bug', 'payment', 'ui')
('payment', 'performance')
('performance', 'ui')
('bug', 'performance')
('feature_request',)
('payment', 'support', 'ui')

In [13]:
new_feedback = [
    "The application is slow and payment keeps failing",
    "I cannot login and the interface button is broken",
    "Payment failed and the application crashed",
    "Please add dark mode"
]

In [14]:
new_feedback_tfidf = vectorizer.transform(new_feedback)

In [15]:
predictions = model.predict(new_feedback_tfidf)

predicted_categories = mlb.inverse_transform(predictions)

for text, categories in zip(new_feedback, predicted_categories):

    print("Feedback:", text)
    print("Categories:", categories)
    print()

Feedback: The application is slow and payment keeps failing
Categories: ('payment',)

Feedback: I cannot login and the interface button is broken
Categories: ('login', 'ui')

Feedback: Payment failed and the application crashed
Categories: ('payment',)

Feedback: Please add dark mode
Categories: ('feature_request',)